### ISSUE TITLE
External database error - "scheduled_tasks" does not exist

### ISSUE THREAD

**Issue by decus** [anvil-works/anvil-runtime#19]
Hi,

I created the Hello_World sample in the online editor, exported it and ran locally with `anvil-app-server --app Hello_World` and everything worked as expected.

I spun up a local standalone Postgres database and tried to use that with the same app: `anvil-app-server --app Hello_World --database "jdbc:postgresql://localhost/<db>?user=<user>&password=<pass>"`

And am getting this error:
```
Found Anvil App Server JAR in package directory
Found 0 migration(s) for (base runtime) DB.
Executing Anvil migrations...
Database currently at "2019-09-23-B-denormalise-app-sessions"
0 migration(s) to perform.
Migration complete.
[ERROR anvil.app-server.run] #error {
 :cause ERROR: relation "scheduled_tasks" does not exist
  Position: 41
 :via
 [{:type org.postgresql.util.PSQLException
   :message ERROR: relation "scheduled_tasks" does not exist
  Position: 41
   :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse QueryExecutorImpl.java 2497]}]
 :trace
 [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse QueryExecutorImpl.java 2497]
  [org.postgresql.core.v3.QueryExecutorImpl processResults QueryExecutorImpl.java 2233]
  [org.postgresql.core.v3.QueryExecutorImpl execute QueryExecutorImpl.java 310]
  [org.postgresql.jdbc.PgStatement executeInternal PgStatement.java 446]
  [org.postgresql.jdbc.PgStatement execute PgStatement.java 370]
  [org.postgresql.jdbc.PgPreparedStatement executeWithFlags PgPreparedStatement.java 149]
  [org.postgresql.jdbc.PgPreparedStatement executeQuery PgPreparedStatement.java 108]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 498]
  [net.ttddyy.dsproxy.proxy.StatementProxyLogic performQueryExecutionListener StatementProxyLogic.java 316]
  [net.ttddyy.dsproxy.proxy.StatementProxyLogic access$700 StatementProxyLogic.java 37]
  [net.ttddyy.dsproxy.proxy.StatementProxyLogic$1 execute StatementProxyLogic.java 123]
  [net.ttddyy.dsproxy.listener.MethodExecutionListenerUtils invoke MethodExecutionListenerUtils.java 42]
  [net.ttddyy.dsproxy.proxy.StatementProxyLogic invoke StatementProxyLogic.java 120]
  [net.ttddyy.dsproxy.proxy.jdk.PreparedStatementInvocationHandler invoke PreparedStatementInvocationHandler.java 37]
  [com.sun.proxy.$Proxy4 executeQuery nil -1]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery NewProxyPreparedStatement.java 353]
  [clojure.java.jdbc$execute_query_with_params invokeStatic jdbc.clj 1079]
  [clojure.java.jdbc$execute_query_with_params invoke jdbc.clj 1073]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic jdbc.clj 1095]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke jdbc.clj 1082]
  [clojure.java.jdbc$query invokeStatic jdbc.clj 1171]
  [clojure.java.jdbc$query invoke jdbc.clj 1133]
  [clojure.java.jdbc$query invokeStatic jdbc.clj 1149]
  [clojure.java.jdbc$query invoke jdbc.clj 1133]
  [anvil.runtime.cron$update_cron_jobs_BANG_$fn__5640$fn__5641 invoke cron.clj 67]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic jdbc.clj 806]
  [clojure.java.jdbc$db_transaction_STAR_ invoke jdbc.clj 776]
  [clojure.java.jdbc$db_transaction_STAR_ invokeStatic jdbc.clj 841]
  [clojure.java.jdbc$db_transaction_STAR_ invoke jdbc.clj 776]
  [anvil.runtime.cron$update_cron_jobs_BANG_$fn__5640 invoke cron.clj 66]
  [anvil.runtime.cron$update_cron_jobs_BANG_ invokeStatic cron.clj 66]
  [anvil.runtime.cron$update_cron_jobs_BANG_ invoke cron.clj 65]
  [anvil.app_server.run$load_main_app invokeStatic run.clj 100]
  [anvil.app_server.run$load_main_app invoke run.clj 93]
  [anvil.app_server.run$_main invokeStatic run.clj 429]
  [anvil.app_server.run$_main doInvoke run.clj 224]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [anvil.app_server.run main nil -1]]}
```

I assume that the migrations to setup the `scheduled_tasks` table aren't being applied - any idea on how I should do that? I can see the tables defined in the builtin Postgres database but feel that it would be too hacky to manually apply those definitions to my new standalone database.

For reference here is my `anvil.yaml`:
```
allow_embedding: false
package_name: Hello_World
db_schema:
- name: Users
  id: 64914
  python_name: users
  columns:
    BKbqJK5LK_g=:
      name: last_login
      type: datetime
      admin_ui: {order: 3, width: 200}
    _GYmkUpHj4E=:
      name: enabled
      type: bool
      admin_ui: {order: 1, width: 100}
    iBV4NpzRhe8=:
      name: email
      type: string
      admin_ui: {order: 0, width: 200}
    qpg9O_JnRc0=:
      name: signed_up
      type: datetime
      admin_ui: {order: 2, width: 200}
  access: {python_name: users, app_id: OD6RICKBZAOJ7GN4, server: full, client: none,
    table_id: 64914}
name: Hello World
startup_form: Form1
renamed: true
runtime_options: {version: 2, client_version: '3', server_version: python3-sandbox}
services:
- source: /runtime/services/tables.yml
  client_config: {}
  server_config: {auto_create_missing_columns: false}
- source: /runtime/services/anvil/users.yml
  client_config: {allow_signup: true, enable_automatically: true, use_email: false,
    confirm_email: false, use_google: true}
  server_config: {user_table: users}
- source: /runtime/services/google.yml
  client_config: {}
  server_config: {}
```
