### ISSUE TITLE
Silently failing on schema migration

### ISSUE THREAD

**Issue by groundswel** [anvil-works/anvil-runtime#5]
It seems that though the anvil app server is detecting that it needs to create a new database schema to match the db schema in anvil.yaml file .. I am not sure why it is not actually creating the database tables. 

```
(env) [anvil@centos-s-1vcpu-1gb-sfo2-01 ~]$ anvil-app-server --app AppName 
Found Anvil App Server JAR in package directory
Found 0 migration(s) for (base runtime) DB.
Executing Anvil migrations...
Database currently at "2019-09-23-B-denormalise-app-sessions"
0 migration(s) to perform.
Migration complete.
[INFO  anvil.app-server.tables] Data tables schema out of date. Here is the migration that will run if you restart Anvil with the --auto-migrate command-line flag:
[INFO  anvil.app-server.tables] [{:action :CREATE_TABLES,
  :tables
  [{:name "Users",
    :python_name "users",
    :columns
    {:2VPIoU_AbJA= {:name "confirmed_email", :type "bool"},
     :jDH+c99C97U= {:name "signed_up", :type "datetime"},
     :OEnitU_Fgww= {:name "email", :type "string"},
     :3jjf5ujVRBo= {:name "last_login", :type "datetime"},
     :UI2UuNFwbKE= {:name "password_hash", :type "string"},
     :l5UP2NSaULI= {:name "org_admin", :type "bool"},
     :ElnQjNWzsnI= {:name "org_secret", :type "string"},
     :oR_SZCt6e_8= {:name "enabled", :type "bool"},
     :Upn8nGLgXXc= {:name "email_confirmation_key", :type "string"}},
    :id 43256}
   {:name "Mapps",
    :python_name "mapps",
    :columns
    {:+Ymexr_i19Y= {:name "AppLink", :type "string"},
     :fMrCfXSZTJE= {:name "AppName", :type "string"},
     :qyWimtt13b8= {:name "AppDescription", :type "string"},
     :vAqiX7y_vsY= {:name "AppLogo", :type "media"}},
    :id 43257}
   {:name "Subscriptions",
    :python_name "subscriptions",
    :columns
    {:+Aqae_poB3k= {:name "UnsubscribedOn", :type "datetime"},
     :AfJo5PK3ypY= {:name "Status", :type "bool"},
     :NloOoR9WLHg=
     {:name "User",
      :type "liveObject",
      :backend "anvil.tables.Row",
      :table_id 43256},
     :Y2SA7nVg_Do= {:name "Role", :type "string"},
     :aWRr0oCV16I=
     {:name "App",
      :type "liveObject",
      :backend "anvil.tables.Row",
      :table_id 43257},
     :hVVPlpKw2lk= {:name "Plan", :type "string"},
     :qD9a5z7TB7w= {:name "SubscribedOn", :type "datetime"}},
    :id 43263}]}
 {:action :DELETE_TABLE, :python_name "Users"}
 {:action :DELETE_TABLE, :python_name "MApps"}
 {:action :DELETE_TABLE, :python_name "Subscriptions"}]

[INFO  anvil.app-server.tables] Anvil will now exit. Run with --ignore-invalid-schema to startup anyway.
(env) [anvil@centos-s-1vcpu-1gb-sfo2-01 ~]$ vim AppName/anvil.yaml 
(env) [anvil@centos-s-1vcpu-1gb-sfo2-01 ~]$ anvil-app-server --app AppName --auto-migrate
Found Anvil App Server JAR in package directory
Found 0 migration(s) for (base runtime) DB.
Executing Anvil migrations...
Database currently at "2019-09-23-B-denormalise-app-sessions"
0 migration(s) to perform.
Migration complete.
[INFO  anvil.core.server] HTTP Server running on port 3030
[INFO  anvil.app-server.run] App URL:  http://localhost:3030
[INFO  anvil.app-server.dispatch] Launching built-in downlink...
[ERROR anvil.app-server.run] Failed to start mail server on port 25 - this application will not be able to receive email:  java.net.BindException: Permission denied (Bind failed)
[INFO  anvil.app-server.run] SMTP Server running on port 25
Connecting to ws://localhost:3030/_/downlink
Anvil websocket open
[INFO  anvil.executors.downlink] Downlink client connected with spec {:runtime "python3-full", :session_id "39l6SLgVHEZ50ovMUUnn"}
Downlink authenticated OK
[TRACE anvil.runtime.util] Creating new session oyhixitc3z7d3xtuetjts42d for app AppName replacing NONE (new session)
[DEBUG anvil.runtime.server] Serving app AppName
[INFO  anvil.app-server.run] [LOG :new-session] {:type browser}
[TRACE anvil.runtime.util] Using existing session oyhixitc3z7d3xtuetjts42d (last accessed 1589059140817, app id AppName)
[DEBUG anvil.dispatcher.core] Dispatch! get_all_apps for AppName
Calling function 'get_all_apps' for app 'AppName' (ID client-SlfJ5uZVdq1ooFKdChEU4Q==)
[DEBUG anvil.dispatcher.core] Dispatch! anvil.private.tables.get_app_tables for AppName
Worker terminated for IDs set() (return code -15)
[ERROR anvil.app-server.run] Error report from client code:
AnvilWrappedError: No such app table: 'mapps'
Traceback:
  /home/anvil/env/lib64/python3.6/site-packages/anvil_downlink_worker/anvil/tables/__init__.py:20

  /home/anvil/AppName/server_code/basic_utils.py:24

  app/AppName/AppDashboard_v1.py:15

  app/AppName/splash_1.py:32
```

**Comment by meredydd** [comment]
Hi @groundswel, can you provide a reproduction case? (Two anvil.yaml files,
where if you run one then the other, you get this error.)

**Comment by groundswel** [comment]
I just took the original anvil.yaml and appended the db_schema at the end. 
```
services:
- source: /runtime/services/tables.yml
  client_config: {}
  server_config: {auto_create_missing_columns: false}
- source: /runtime/services/anvil/users.yml
  client_config: {allow_signup: true, enable_automatically: true, use_email: true,
    confirm_email: true}
  server_config: {user_table: 43256}
startup: {type: form, module: splash_1}
package_name: Igniter
allow_embedding: false
name: Igniter
runtime_options: {version: 2, client_version: '3', server_version: python3-sandbox}
metadata: {}
startup_form: cc_token
native_deps: {head_html: ''}
dependency_order: []
dependency_code: {}
renamed: true
db_schema:
- name: Users
  python_name: users
  columns:
    OEnitU_Fgww=:
      name: email
      type: string
    ElnQjNWzsnI=:
      name: org_secret
      type: string
    2VPIoU_AbJA=:
      name: confirmed_email
      type: bool
    oR_SZCt6e_8=:
      name: enabled
      type: bool
    3jjf5ujVRBo=:
      name: last_login
      type: datetime
    l5UP2NSaULI=:
      name: org_admin
      type: bool
    Upn8nGLgXXc=:
      name: email_confirmation_key
      type: string
    UI2UuNFwbKE=:
      name: password_hash
      type: string
    jDH+c99C97U=:
      name: signed_up
      type: datetime
  id: 43256
- name: MApps
  python_name: mapps
  columns:
    +Ymexr_i19Y=:
      name: AppLink
      type: string
    fMrCfXSZTJE=:
      name: AppName
      type: string
    qyWimtt13b8=:
      name: AppDescription
      type: string
    vAqiX7y_vsY=:
      name: AppLogo
      type: media
  id: 43257
- name: Subscriptions
  python_name: subscriptions
  columns:
    +Aqae_poB3k=:
      name: UnsubscribedOn
      type: datetime
    AfJo5PK3ypY=:
      name: Status
      type: bool
    NloOoR9WLHg=:
      name: User
      type: liveObject
      backend: anvil.tables.Row
      table_id: 43256
    Y2SA7nVg_Do=:
      name: Role
      type: string
    aWRr0oCV16I=:
      name: App
      type: liveObject
      backend: anvil.tables.Row
      table_id: 43257
    hVVPlpKw2lk=:
      name: Plan
      type: string
    qD9a5z7TB7w=:
      name: SubscribedOn
      type: datetime
  id: 43263
```
