### ISSUE TITLE
No users table error

### ISSUE THREAD

**Issue by andersgs** [anvil-works/anvil-runtime#9]
Hello. 

I am working from the example `services` to configure a users service in a dummy test app (based on the app-structure.yaml docs), but it seems that no `users` table is created. Here is the print out when the app is first called:

```
Database is uninitialised. Setting up Anvil database from scratch...
Setup complete.
[INFO  anvil.core.server] HTTP Server running on port 3030
[INFO  anvil.app-server.run] App URL:  http://localhost:3030
[INFO  anvil.app-server.dispatch] Launching built-in downlink...
[INFO  anvil.app-server.run] SMTP Server running on port 25
Connecting to ws://localhost:3030/_/downlink
Anvil websocket open
```

Here is the `anvil.yaml`:

```
dependencies: []
services:
- source: /runtime/services/tables.yml
  client_config: {}
  server_config: {auto_create_missing_columns: false}
- source: /runtime/services/anvil/users.yml
  client_config: {use_microsoft: false, require_secure_passwords: true, share_login_status: false,
    use_email: true, allow_remember_me: true, allow_signup: true, enable_automatically: false,
    confirm_email: false, remember_me_days: 7, use_google: false, use_facebook: false}
  server_config: {user_table: 'users'}
package_name: MyCRUDApp
allow_embedding: false
name: My CRUD App
runtime_options: {version: 2, client_version: '3', server_version: python3-sandbox}
metadata: {}
startup_form: Form1
db_schema:
- name: tasks
  id: 12345
  python_name: tasks
  columns:
    E9e2ASS2uyU=:
      name: name
      type: string
      admin_ui: {order: 0, width: 200}
    Lk958fQHwJ0=:
      name: complete
      type: bool
      admin_ui: {order: 0, width: 200}
  access: {python_name: tasks, app_id: MyCRUDApp, server: full, client: none,
    table_id: 12345}
renamed: true
```

This is the code that I am trying to run:
```
print("Adding admin user")
app_tables.users.add_row(email = "app-ruler@example.com",
password="my_super_secret_password",
enable=True)
```

And, here is the error I am getting: 

```
[ERROR anvil.app-server.run] Error report from client code:
AnvilWrappedError: No such app table: 'users'
```

Unsure why the error is in the client code. The call is done in a server module.

Do I need to explicitly create a schema for the table?

I am using version 1.1 of app server and python 3.7.7.

Thank you.

Anders.
